### PR TITLE
Added open/unlock charge port to menu: "Open Port"

### PR DESCRIPTION
**Pull request by jaatuli**
This is the feature I am most needing, as it is really annoing to get your phone out to unlock the charge cable on non-Tesla charge points.

### CODE REVIEW

**Review by tomeczko — APPROVED** [review]
+1 from me :)

**Review by n-gineer — CHANGES_REQUESTED** [review]
It may be helpful to fix your edits to manifest.xml to clearly show you only added the Finnish language line; code tracking indicates you completely deleted and rewrote the file.

**Comment by srwalter** [comment]
I cherry-picked the commit that adds the charge port.  Please rebase your Finnish language commits if you still would like them to be integrated

**Comment by jaatuli** [comment]
I am not very familiar with the pull requests. I can create the Finnish translation as a separate pull request, so maybe it is more clear.

**Pull request closed without merging**
